### ISSUE TITLE
This is a token grabber.

### ISSUE THREAD

**Issue by XranaDev** [vroomyy/DiscordNuker#1]
Hello, this is obvious, it is a token grabber. No one would ever ask you to put something in console unless they are trying to hack you.

**Comment by Keathiz** [comment]
> 
> 
> Hello, this is obvious, it is a token grabber. No one would ever ask you to put something in console unless they are trying to hack you.

Its literally open source u fuck head, just look at the code, how is it a token grabber? And you call yourself a dev? Jfc get outta here with that you little skid!

**Comment by vroomyy** [comment]
Its not an tokengrabber read the code again please

**Comment by XranaDev** [comment]
> Its not an tokengrabber read the code again please

Ummm, let me show you a piece of code.

`function patchData(url = '', data = {}) {
    const response = fetch(url, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'Authorization':  FindModule("getToken").getToken(),
        'User-agent': navigator.userAgent,
        'x-super-properties': FindModule("getSuperPropertiesBase64").getSuperPropertiesBase64()
      },
      body: JSON.stringify(data)
    });
    return response;
}`

Can you explain this? Thanks.

**Comment by stop-bark** [comment]
> 
> 
> > Its not an tokengrabber read the code again please
> 
> Ummm, let me show you a piece of code.
> 
> `function patchData(url = '', data = {}) { const response = fetch(url, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'Authorization': FindModule("getToken").getToken(), 'User-agent': navigator.userAgent, 'x-super-properties': FindModule("getSuperPropertiesBase64").getSuperPropertiesBase64() }, body: JSON.stringify(data) }); return response; }`
> 
> Can you explain this? Thanks.

You dont specify a token yourself, it takes your user's token so it can login to the account to actually nuke it u monkey.

**Comment by XranaDev** [comment]
> > > Its not an tokengrabber read the code again please
> > 
> > 
> > Ummm, let me show you a piece of code.
> > `function patchData(url = '', data = {}) { const response = fetch(url, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'Authorization': FindModule("getToken").getToken(), 'User-agent': navigator.userAgent, 'x-super-properties': FindModule("getSuperPropertiesBase64").getSuperPropertiesBase64() }, body: JSON.stringify(data) }); return response; }`
> > Can you explain this? Thanks.
> 
> You dont specify a token yourself, it takes your user's token so it can login to the account to actually nuke it u monkey.
> 
> _Edit:_ And also if you really think its a token grabber, then show me where the fuck the webhook link is.

But would it do it in the browser?
